/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalisadorRouteImport } from './routes/analisador'
import { Route as AnalisarPrintRouteImport } from './routes/analisar-print'
import { Route as AprendizadoRouteImport } from './routes/aprendizado'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as ClaudeRouteImport } from './routes/claude'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ErrosRouteImport } from './routes/erros'
import { Route as GerenciamentoRouteImport } from './routes/gerenciamento'
import { Route as HistoricoAnalisesRouteImport } from './routes/historico-analises'
import { Route as OperacaoAoVivoRouteImport } from './routes/operacao-ao-vivo'
import { Route as ValidacaoT4RouteImport } from './routes/validacao-t4'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisadorRoute = AnalisadorRouteImport.update({
  id: '/analisador',
  path: '/analisador',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisarPrintRoute = AnalisarPrintRouteImport.update({
  id: '/analisar-print',
  path: '/analisar-print',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendizadoRoute = AprendizadoRouteImport.update({
  id: '/aprendizado',
  path: '/aprendizado',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeRoute = ClaudeRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrosRoute = ErrosRouteImport.update({
  id: '/erros',
  path: '/erros',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciamentoRoute = GerenciamentoRouteImport.update({
  id: '/gerenciamento',
  path: '/gerenciamento',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoAnalisesRoute = HistoricoAnalisesRouteImport.update({
  id: '/historico-analises',
  path: '/historico-analises',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoAoVivoRoute = OperacaoAoVivoRouteImport.update({
  id: '/operacao-ao-vivo',
  path: '/operacao-ao-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidacaoT4Route = ValidacaoT4RouteImport.update({
  id: '/validacao-t4',
  path: '/validacao-t4',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisador': typeof AnalisadorRoute
  '/analisar-print': typeof AnalisarPrintRoute
  '/aprendizado': typeof AprendizadoRoute
  '/backtest': typeof BacktestRoute
  '/biblioteca': typeof BibliotecaRoute
  '/claude': typeof ClaudeRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/erros': typeof ErrosRoute
  '/gerenciamento': typeof GerenciamentoRoute
  '/historico-analises': typeof HistoricoAnalisesRoute
  '/operacao-ao-vivo': typeof OperacaoAoVivoRoute
  '/validacao-t4': typeof ValidacaoT4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisador': typeof AnalisadorRoute
  '/analisar-print': typeof AnalisarPrintRoute
  '/aprendizado': typeof AprendizadoRoute
  '/backtest': typeof BacktestRoute
  '/biblioteca': typeof BibliotecaRoute
  '/claude': typeof ClaudeRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/erros': typeof ErrosRoute
  '/gerenciamento': typeof GerenciamentoRoute
  '/historico-analises': typeof HistoricoAnalisesRoute
  '/operacao-ao-vivo': typeof OperacaoAoVivoRoute
  '/validacao-t4': typeof ValidacaoT4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisador': typeof AnalisadorRoute
  '/analisar-print': typeof AnalisarPrintRoute
  '/aprendizado': typeof AprendizadoRoute
  '/backtest': typeof BacktestRoute
  '/biblioteca': typeof BibliotecaRoute
  '/claude': typeof ClaudeRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/erros': typeof ErrosRoute
  '/gerenciamento': typeof GerenciamentoRoute
  '/historico-analises': typeof HistoricoAnalisesRoute
  '/operacao-ao-vivo': typeof OperacaoAoVivoRoute
  '/validacao-t4': typeof ValidacaoT4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisador'
    | '/analisar-print'
    | '/aprendizado'
    | '/backtest'
    | '/biblioteca'
    | '/claude'
    | '/configuracoes'
    | '/erros'
    | '/gerenciamento'
    | '/historico-analises'
    | '/operacao-ao-vivo'
    | '/validacao-t4'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analisador'
    | '/analisar-print'
    | '/aprendizado'
    | '/backtest'
    | '/biblioteca'
    | '/claude'
    | '/configuracoes'
    | '/erros'
    | '/gerenciamento'
    | '/historico-analises'
    | '/operacao-ao-vivo'
    | '/validacao-t4'
  id:
    | '__root__'
    | '/'
    | '/analisador'
    | '/analisar-print'
    | '/aprendizado'
    | '/backtest'
    | '/biblioteca'
    | '/claude'
    | '/configuracoes'
    | '/erros'
    | '/gerenciamento'
    | '/historico-analises'
    | '/operacao-ao-vivo'
    | '/validacao-t4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisadorRoute: typeof AnalisadorRoute
  AnalisarPrintRoute: typeof AnalisarPrintRoute
  AprendizadoRoute: typeof AprendizadoRoute
  BacktestRoute: typeof BacktestRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ClaudeRoute: typeof ClaudeRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ErrosRoute: typeof ErrosRoute
  GerenciamentoRoute: typeof GerenciamentoRoute
  HistoricoAnalisesRoute: typeof HistoricoAnalisesRoute
  OperacaoAoVivoRoute: typeof OperacaoAoVivoRoute
  ValidacaoT4Route: typeof ValidacaoT4Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisador': {
      id: '/analisador'
      path: '/analisador'
      fullPath: '/analisador'
      preLoaderRoute: typeof AnalisadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisar-print': {
      id: '/analisar-print'
      path: '/analisar-print'
      fullPath: '/analisar-print'
      preLoaderRoute: typeof AnalisarPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprendizado': {
      id: '/aprendizado'
      path: '/aprendizado'
      fullPath: '/aprendizado'
      preLoaderRoute: typeof AprendizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude': {
      id: '/claude'
      path: '/claude'
      fullPath: '/claude'
      preLoaderRoute: typeof ClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erros': {
      id: '/erros'
      path: '/erros'
      fullPath: '/erros'
      preLoaderRoute: typeof ErrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerenciamento': {
      id: '/gerenciamento'
      path: '/gerenciamento'
      fullPath: '/gerenciamento'
      preLoaderRoute: typeof GerenciamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico-analises': {
      id: '/historico-analises'
      path: '/historico-analises'
      fullPath: '/historico-analises'
      preLoaderRoute: typeof HistoricoAnalisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao-ao-vivo': {
      id: '/operacao-ao-vivo'
      path: '/operacao-ao-vivo'
      fullPath: '/operacao-ao-vivo'
      preLoaderRoute: typeof OperacaoAoVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validacao-t4': {
      id: '/validacao-t4'
      path: '/validacao-t4'
      fullPath: '/validacao-t4'
      preLoaderRoute: typeof ValidacaoT4RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisadorRoute: AnalisadorRoute,
  AnalisarPrintRoute: AnalisarPrintRoute,
  AprendizadoRoute: AprendizadoRoute,
  BacktestRoute: BacktestRoute,
  BibliotecaRoute: BibliotecaRoute,
  ClaudeRoute: ClaudeRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ErrosRoute: ErrosRoute,
  GerenciamentoRoute: GerenciamentoRoute,
  HistoricoAnalisesRoute: HistoricoAnalisesRoute,
  OperacaoAoVivoRoute: OperacaoAoVivoRoute,
  ValidacaoT4Route: ValidacaoT4Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
