/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAtasRouteImport } from './routes/_authenticated/atas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCopilotoRouteImport } from './routes/_authenticated/copiloto'
import { Route as AuthenticatedCurriculoRouteImport } from './routes/_authenticated/curriculo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosticoRouteImport } from './routes/_authenticated/diagnostico'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMemoriaRouteImport } from './routes/_authenticated/memoria'
import { Route as AuthenticatedMinhaIaRouteImport } from './routes/_authenticated/minha-ia'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedReunioesRouteImport } from './routes/_authenticated/reunioes'
import { Route as AuthenticatedSimuladorRouteImport } from './routes/_authenticated/simulador'
import { Route as AuthenticatedTeleprompterRouteImport } from './routes/_authenticated/teleprompter'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtasRoute = AuthenticatedAtasRouteImport.update({
  id: '/atas',
  path: '/atas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCopilotoRoute = AuthenticatedCopilotoRouteImport.update({
  id: '/copiloto',
  path: '/copiloto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCurriculoRoute = AuthenticatedCurriculoRouteImport.update({
  id: '/curriculo',
  path: '/curriculo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticoRoute =
  AuthenticatedDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoriaRoute = AuthenticatedMemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaIaRoute = AuthenticatedMinhaIaRouteImport.update({
  id: '/minha-ia',
  path: '/minha-ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReunioesRoute = AuthenticatedReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimuladorRoute = AuthenticatedSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeleprompterRoute =
  AuthenticatedTeleprompterRouteImport.update({
    id: '/teleprompter',
    path: '/teleprompter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/atas': typeof AuthenticatedAtasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/copiloto': typeof AuthenticatedCopilotoRoute
  '/curriculo': typeof AuthenticatedCurriculoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/memoria': typeof AuthenticatedMemoriaRoute
  '/minha-ia': typeof AuthenticatedMinhaIaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reunioes': typeof AuthenticatedReunioesRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/teleprompter': typeof AuthenticatedTeleprompterRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/atas': typeof AuthenticatedAtasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/copiloto': typeof AuthenticatedCopilotoRoute
  '/curriculo': typeof AuthenticatedCurriculoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/memoria': typeof AuthenticatedMemoriaRoute
  '/minha-ia': typeof AuthenticatedMinhaIaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/reunioes': typeof AuthenticatedReunioesRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/teleprompter': typeof AuthenticatedTeleprompterRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/_authenticated/atas': typeof AuthenticatedAtasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/copiloto': typeof AuthenticatedCopilotoRoute
  '/_authenticated/curriculo': typeof AuthenticatedCurriculoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/memoria': typeof AuthenticatedMemoriaRoute
  '/_authenticated/minha-ia': typeof AuthenticatedMinhaIaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/reunioes': typeof AuthenticatedReunioesRoute
  '/_authenticated/simulador': typeof AuthenticatedSimuladorRoute
  '/_authenticated/teleprompter': typeof AuthenticatedTeleprompterRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/atas'
    | '/configuracoes'
    | '/copiloto'
    | '/curriculo'
    | '/dashboard'
    | '/diagnostico'
    | '/home'
    | '/memoria'
    | '/minha-ia'
    | '/perfil'
    | '/relatorios'
    | '/reunioes'
    | '/simulador'
    | '/teleprompter'
    | '/templates'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/atas'
    | '/configuracoes'
    | '/copiloto'
    | '/curriculo'
    | '/dashboard'
    | '/diagnostico'
    | '/home'
    | '/memoria'
    | '/minha-ia'
    | '/perfil'
    | '/relatorios'
    | '/reunioes'
    | '/simulador'
    | '/teleprompter'
    | '/templates'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/_authenticated/atas'
    | '/_authenticated/configuracoes'
    | '/_authenticated/copiloto'
    | '/_authenticated/curriculo'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostico'
    | '/_authenticated/home'
    | '/_authenticated/memoria'
    | '/_authenticated/minha-ia'
    | '/_authenticated/perfil'
    | '/_authenticated/relatorios'
    | '/_authenticated/reunioes'
    | '/_authenticated/simulador'
    | '/_authenticated/teleprompter'
    | '/_authenticated/templates'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atas': {
      id: '/_authenticated/atas'
      path: '/atas'
      fullPath: '/atas'
      preLoaderRoute: typeof AuthenticatedAtasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copiloto': {
      id: '/_authenticated/copiloto'
      path: '/copiloto'
      fullPath: '/copiloto'
      preLoaderRoute: typeof AuthenticatedCopilotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculo': {
      id: '/_authenticated/curriculo'
      path: '/curriculo'
      fullPath: '/curriculo'
      preLoaderRoute: typeof AuthenticatedCurriculoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico': {
      id: '/_authenticated/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof AuthenticatedDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memoria': {
      id: '/_authenticated/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof AuthenticatedMemoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-ia': {
      id: '/_authenticated/minha-ia'
      path: '/minha-ia'
      fullPath: '/minha-ia'
      preLoaderRoute: typeof AuthenticatedMinhaIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reunioes': {
      id: '/_authenticated/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof AuthenticatedReunioesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulador': {
      id: '/_authenticated/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof AuthenticatedSimuladorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teleprompter': {
      id: '/_authenticated/teleprompter'
      path: '/teleprompter'
      fullPath: '/teleprompter'
      preLoaderRoute: typeof AuthenticatedTeleprompterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtasRoute: typeof AuthenticatedAtasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCopilotoRoute: typeof AuthenticatedCopilotoRoute
  AuthenticatedCurriculoRoute: typeof AuthenticatedCurriculoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticoRoute: typeof AuthenticatedDiagnosticoRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMemoriaRoute: typeof AuthenticatedMemoriaRoute
  AuthenticatedMinhaIaRoute: typeof AuthenticatedMinhaIaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedReunioesRoute: typeof AuthenticatedReunioesRoute
  AuthenticatedSimuladorRoute: typeof AuthenticatedSimuladorRoute
  AuthenticatedTeleprompterRoute: typeof AuthenticatedTeleprompterRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtasRoute: AuthenticatedAtasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCopilotoRoute: AuthenticatedCopilotoRoute,
  AuthenticatedCurriculoRoute: AuthenticatedCurriculoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticoRoute: AuthenticatedDiagnosticoRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMemoriaRoute: AuthenticatedMemoriaRoute,
  AuthenticatedMinhaIaRoute: AuthenticatedMinhaIaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedReunioesRoute: AuthenticatedReunioesRoute,
  AuthenticatedSimuladorRoute: AuthenticatedSimuladorRoute,
  AuthenticatedTeleprompterRoute: AuthenticatedTeleprompterRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
